apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ip88
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0022-tenant/ci1t-43256-0022-app/devfile-sample-ip88@sha256:b79737516eb7308f24c09c715ca142baea426edc4397b7bdf7febeb5bab4e411
        name: my-nodejs
        resources: {}
status: {}
